/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.franciscoedno.simplex;

import java.io.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Queue;
import java.util.Random;
import java.util.concurrent.ConcurrentLinkedQueue;

public class App {
    public static void main(String[] args) throws IOException {
        Queue<String> messages = new ConcurrentLinkedQueue<>();
        QuotesChannel channel = new QuotesChannel(messages);

        new Thread(new Consumer(channel)).start();
        new Thread(new Producer(channel, new QuoteBase())).start();
    }
}
